server:
  port: 2333
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      soundcloud: true
    youtube:
      playlistLoadLimit: 6
      searchEnabled: true